### ISSUE TITLE
Loading H2 Class from Another Plugin

### ISSUE THREAD

**Issue by KASUNHapangama** [KASUNHapangama/DiscordLeaderboards#20]
[02:22:01 WARN]: [DLeaderboards] Loaded class us.ajg0702.leaderboards.libs.h2.Driver from ajLeaderboards v2.7.0 which is not a depend or softdepend of this plugin.
[02:22:01 WARN]: [ajLeaderboards] Loaded class org.h2.mvstore.tx.VersionedValueType$Factory from DiscordLeaderboards v0.1.2 which is not a depend or softdepend of this plugin.

**Comment by KASUNHapangama** [comment]
## Console Log

[08:59:19 INFO]: =========================================
[08:59:19 INFO]: Discord Leaderboards Plugin Started !
[08:59:19 INFO]: PlaceholderApi Hooked!
[08:59:19 INFO]: DiscordSRV Hooked!
[08:59:19 INFO]: =========================================
[08:59:19 WARN]: [DLeaderboards] Loaded class tk.bluetree242.discordsrvutils.dependencies.hsqldb.jdbc.JDBCDriver from DiscordSRVUtils v1.2.12 which is not a depend or softdepend of this plugin.
[08:59:19 WARN]: [DLeaderboards] Loaded class us.ajg0702.leaderboards.libs.h2.Driver from ajLeaderboards v2.7.0 which is not a depend or softdepend of this plugin.
[08:59:19 WARN]: [ajLeaderboards] Loaded class org.h2.mvstore.db.NullValueDataType from DiscordLeaderboards v0.1.2 which is not a depend or softdepend of this plugin.
[08:59:19 ERROR]: [DLeaderboards] Failed to Connect H2 Database ! [code : 07]
[08:59:19 ERROR]: Error occurred while enabling DiscordLeaderboards v0.1.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because the return value of "org.kasun.discordleaderboards.Database.Database.getConnection()" is null
        at org.kasun.discordleaderboards.Database.Database.initializeDatabase(Database.java:64) ~[DiscordLeaderboards-Beta-1.2.jar:?]
        at org.kasun.discordleaderboards.Database.DatabaseManager.<init>(DatabaseManager.java:7) ~[DiscordLeaderboards-Beta-1.2.jar:?]
        at org.kasun.discordleaderboards.MainManager.<init>(MainManager.java:26) ~[DiscordLeaderboards-Beta-1.2.jar:?]
        at org.kasun.discordleaderboards.DiscordLeaderboards.onEnable(DiscordLeaderboards.java:20) ~[DiscordLeaderboards-Beta-1.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:59:19 INFO]: [DLeaderboards] Disabling DiscordLeaderboards v0.1.2
[08:59:19 INFO]: [Dleaderboards] Plugin ShutDown

**Comment by KASUNHapangama** [comment]
Fixed with beta-1.3
